print("trabajo supervisado")
print("07/09/2023")
print("Alejandro Echegoyen")
print("Mi segundo programa")
sNombre= input("ingrese su nombre")
sEdad= input("por favor ingreso su edad")
sCarrera= input("por favor ingrese su carrera")
sCarne= input("por favor ingresar su carne")

print("nombre",sNombre)
print("edad", sEdad)
print("Carrera", sCarrera)
print("carne", sCarne)

print("soy" +sNombre, "tengo" +sEdad, "años y estudio la carrera de" +sCarrera, "Mi numero de carnet es: "+sCarne )
